name: Scheduled Publish

on:
  schedule:
    - cron: '22 4 * * 0'  # Weekly build
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Ensure all matrix jobs continue even if one fails
  matrix:
    include:
      - role: "blue"
        job_name: "ğŸ’™ Blue Teamer ğŸ’™"
      - role: "bugbounty"
        job_name: "ğŸ Bug Bounty Hunter ğŸ"
      - role: "cracker"
        job_name: "ğŸ˜ Cracker Specialist ğŸ˜"
      - role: "dos"
        job_name: "ğŸ’€ DoS Tester ğŸ’€"
      - role: "student"
        job_name: "ğŸ“ Enthusiast Student ğŸ“"
      - role: "forensic"
        job_name: "ğŸ” Forensic Analyst ğŸ”"
      - role: "malware"
        job_name: "ğŸ¦  Malware Analyst ğŸ¦ "
      - role: "mobile"
        job_name: "ğŸ“± Mobile Analyst ğŸ“±"
      - role: "network"
        job_name: "ğŸŒ Network Analyst ğŸŒ"
      - role: "osint"
        job_name: "ğŸ•µï¸ OSINT Specialist ğŸ•µï¸"
      - role: "red"
        job_name: "â¤ï¸ Red Teamer â¤ï¸"
      - role: "web"
        job_name: "ğŸ•¸ï¸ Web Pentester ğŸ•¸ï¸"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ${{ matrix.role }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.role }}
          push: true
          tags: athenaos/${{ matrix.role }}:latest
